### ISSUE TITLE
Balloons only support a single \n

### ISSUE THREAD

**Issue by simonkolotov** [dov/giv#60]
Hi Dov, long time.
Currently balloons in giv only check for one '\n' in the string, the rest are written out literaly.
I know this can be circumvented by multiple 'balloon' lines, but if you already support breaking the lines by \n, it makes sense to check for all of them.
(It also makes it simpler to write a single ballon when creating a giv file from script rather than starting to break up the string into multiple strings...)

Thanks

**Comment by dov** [comment]
Indeed far too long. :-)

Glad to hear that you still use giv.

Oops. Indeed a nice bug. I'll fix it asap.

**Comment by simonkolotov** [comment]
I'm actually implementing it as the main visualizer for a project

Simon Kolotov

**Comment by dov** [comment]
Fixed in the following commit on branch master:
```
commit e22c919a826a13bfc12b7784af520a45a9b86126
Author: Dov Grobgeld <dov.grobgeld@gmail.com>
Date:   Wed Jun 14 23:10:54 2023 +0300

    Fixed bug with multi-line balloons. #60
```
